language: python
python:
- 3.6
- 3.7
- 3.8
- 3.9
env:
- TOXENV=py
install:
- pip install -U tox-travis
- pip install -r requirements_dev.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: Cg6gBwNFeLQeIjCwdhhvEMf37m+0LrGRyunrjqqwgla7Co5ImgHzg4gVzeT/R18j9K2I2Tf12gPhFt7ZF1nfoBjwGJ7eciB+4O5YK2sP/1C3hGpuyl6twRajTa6RA6IfHJ4S7FZA7TbyZ4Y7BQjd9tf8wTC3DFqu2woYwbWw3uGzJ9AJHkbT8bj8lBVBA4ETzu5Y7EuwGbXLwVi5Hx87DezNAh9iV5imYco7w3lOPY+3S33wS262zVNVpeMuFTEOyPwMWv2oTqmsQL1yRYxEyAUdJKSPcTtLPxP0WRWxwvtOsH9lhn5vz+j8c6fMXOd9Oub0wwp6W1MEEZcIN+/wx2uDpYFaoEe04Zq9TDIMbxGIjqvK3rGrWunbjsUI4I7ldCARtJAp40AAzdWEI4/5ekG1iZDhmSCLHXQs4tyewDf6cUNtyLdr0b2aENQTsA9Y2dEqbrLGQFTcwjdQTkrE+3awDTkwrMfVmLmjRMvb7NIQRn4BLSu9qs/6os/tjpY7fxBak0H+N6LgUgepq34lz499moNB8MtCgcslw08IYE716/+Qzw6DDwlurmbulLUCdESbCaIBFGY9Zx8o3WrOjxb9/xBrjJPbU4MbvXrMN4Xl1Z3CF19tI7y2uCHFhT4zeNOaHmhNLlthXnB3Hzx9o//e64yuPZFxs2apgqMa5aA=
  skip_cleanup: true
  skip_existing: true
  distributions: sdist
  on:
    tags: true
    repo: fbrundu/pymrmr
    condition: "$TOXENV == py"
